spring:
  application:
    name: Contacts
  thymeleaf:
    cache: true
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  security:
    user:
      name: ${APP_USERNAME}
      password: ${APP_PASSWORD}
