spring:
  security:
    user:
      name: admin
      password: admin
  datasource:
    url: jdbc:postgresql://localhost:5432/contacts
    username: contacts
    password: contacts
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/resources/templates/
      additional-exclude: "**/*.html"
  web:
    resources:
      static-locations:
        - file:src/main/resources/static/
        - classpath:/static/
      cache:
        period: 0
      chain:
        cache: false
