spring:
  application:
    name: Contacts
  thymeleaf:
    cache: true
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  security:
    user:
      name: ${APP_USERNAME}
      password: ${APP_PASSWORD}
